data/capsule.json

Capsule is a tool meant to share a Kubernetes cluster in a secure way with multiple users, teams, and departments.
Capsule is developed by CLASTIX, an Italian start-up based in Milan specialized in developing tools for k8s.

feat: adding capsule

---

data/ImageGoNord.json
data/daje.json
data/snackjob.json
data/youtube-to-anchorfm.json

Add [Schrodinger-hat](https://github.com/Schrodinger-Hat) projects 😃

feature: add schrodinger-hat project

---

data/kannon.json

fix: set correct site url

---

data/fastify.json

Fastify is a web framework born by two Italians (the [lead maintainers](https://github.com/fastify/fastify#team))

add: fastify

---

data/icaro.json

Icaro is a JVM programming language born as a didactic project

add: Icaro

---

data/kathara.json

Kathará is a lightweight and scalable network emulator based on Docker containers. 
It is used in [many universities](https://www.kathara.org/stories.html) around the world for teaching computer networks. 
It is developed by the [Computer Networks and Security Research Group](https://compunet.ing.uniroma3.it/#!/group/compunet) at Roma Tre University.

add: Kathará

---

data/breathly.json

Added Breathly

---

data/remotebear.json

Added Remotebear

---

data/ordinary-puzzles.json

Added https://ordinarypuzzles.com/

Added Ordinary Puzzles

---

data/pet-therapy.json

App that brings Desktop Pets to macOS

Added project Pet Therapy

---

data/cachegrand.json

The PR adds a cachegrand.json file to the data folder to describe the cachegrand project (of which I am the author).

Add cachegrand.json

---

data/icaro.json

* created the organization
* created the website
* project goals/mission changed

update icaro info

---

data/primait-nuvola.json

* https://github.com/primait/nuvola

add nuvola project

---

.github/workflows/release.yml

**If this is related a issues/PR**

hotifx: release workflow

---

CONTRIBUTING.md

As per my other PR, just found two typos and wanted to help correcting them :)

docs: fixed typos in contributing

---

awesome/opensource/data/cache-candidate.json

**If this is related a issues/PR**

feat: add cache-candidate

---

.github/pull_request_template.md
awesome/companies/data/everli.json
awesome/opensource/data/everli-uppy.json

**If this is related a issues/PR**

Add company Everli and Everli Uppy project

---

awesome/communities/data/ripsters.json
awesome/communities/data/twc-italia.json
awesome/companies/data/sfusoitalia.json
awesome/opensource/data/platformic.json

feat: add awesome items

---

awesome/communities/data/marca-user-group.json

Add Marca User Group community

---

awesome/communities/data/red-hot-cyber.json
awesome/communities/data/startup-italia.json
awesome/companies/data/airlite.json
awesome/companies/data/bending-spoons.json
awesome/companies/data/data-pizza.json
awesome/companies/data/macai.json
awesome/companies/data/neulabs.json
awesome/opensource/data/neulabs-cdk-constructs.json
scripts/check.py

feat: add data and new field

---

awesome/companies/data/noovolari.json

Added Noovolari Company

---

awesome/opensource/data/apivault.json

Added apivault.dev in the opensource projects

---

awesome/communities/data/developers-italia.json

feat: add Developers Italia

---

awesome/opensource/data/galactic-CV-guide.json
awesome/opensource/data/galactic-linkedin-profile-guide.json

feat: add guido penta projects

---

awesome/communities/data/fabio-biondi.json
scripts/check.py

feat: add fabio biondi

---

awesome/communities/data/kubernetes-it.json

feat: add kubernetes it

---

awesome/communities/data/sistemista-italiano.json

feat: add sistemista italiano

---

awesome/companies/data/plick.json

feat: add plick

---

awesome/communities/data/flutter-italia.json

feat: add flutter italia

---

awesome/opensource/data/odoo-italia.json

Add Odoo Italia

---

scripts/render.py

I updated the opensource/readme.md with right url for website.

docs: update opensource/readme.md with right url

---

CONTRIBUTING.md
awesome/digital-nomads/data/bansko.json
scripts/check.py
scripts/notify.py
scripts/render.py

feat(awesome): add notify

---

README.md
awesome/opensource/data/job-offer-bot.json

Added Job Offer Bot to the awesome list
Fixed a typo in the README

feat(awesome): added job offer bot

---

awesome/communities/data/lalocandadeltech.json

I hope I made everything alright :)

feat(communities): added lalocandadeltech.json

---

awesome/opensource/data/lambda-power-tuning.json

feat(opensource): added AWS Lambda Power Tuning

---

awesome/communities/data/fullremote-it.json

feat(communities): added fullremote.it

---

awesome/communities/data/techcompenso.json

feat(communities): added techcompenso

---

awesome/digital-nomads/data/syros.json

feat(digital-nomads): added syros

---

awesome/opensource/data/make-js-component.json

feat(opensource): added make-js-component

---

awesome/companies/data/fotovoltaiconorditalia.json

feat(companies): added Fotovoltaiconorditalia

---

awesome/opensource/data/passkit-generator.json

feat(opensource): added passkit-generator

---

awesome/communities/data/continuous-delivery.json
awesome/communities/data/edo.json

feat(communities): add edo and continuous delivery

---

awesome/opensource/data/version-wizard.json

feat(opensource): added version-wizard

---

awesome/digital-nomads/data/nosybe.json

feat(digital-nomads): added nosybe

---

awesome/communities/data/gitbar.json

feat(communities): added gitbar

---

awesome/opensource/data/fiume.json

feat(opensource): add fiume

---

awesome/opensource/data/serverMan.json

feat(opensource): added ServerMan

---

awesome/communities/data/italian-linux-society.json
awesome/opensource/data/contribute-to-opensource-the-right-way.json
awesome/opensource/data/espanso-typofixer.json
awesome/opensource/data/gbaatm-rebirth.json
awesome/opensource/data/gggg.json
awesome/opensource/data/gh-license.json
awesome/opensource/data/gitapper.json
awesome/opensource/data/glotdict.json
awesome/opensource/data/pydal.json
awesome/opensource/data/share-backported.json
awesome/opensource/data/wordpress-plugin-boilerplate-powered.json

Added the Italian Linux Society and famous personal projects.
About ILS I wasn't sure how to catalog it as the association have Telegram but also a ML and every LUG/association as their own communication channels.

feat(awesome): added Italian Linux Society and famous personal projects

---

awesome/opensource/data/open-profiler.json

feat(opensource): added open-profiler

---

awesome/opensource/data/distrobox.json

Fix https://github.com/89luca89/distrobox/issues/1063

feat(opensource): added Distrobox

---

awesome/digital-nomads/data/bogotà.json

feat(digital-nomads): added bogotà

---

awesome/opensource/data/fusioncache.json

feat(opensource): added FusionCache

---

awesome/opensource/data/fwdctl.json

feat(opensource): added Fwdctl

---

awesome/opensource/data/santo-del-giorno.json

Add Santo Del Giorno Open Source project

feat(opensource): Add santo-del-giorno.json project

---

awesome/opensource/data/nutgram-hydrator.json
awesome/opensource/data/nutgram.json
awesome/opensource/data/xbackbone.json

feat(opensource): add nutgram, hydrator and xbackbone

---

awesome/communities/data/la-brigata-dei-geek-estinti.json

feat(communities): add La Brigata dei Geek Estinti

---

awesome/opensource/data/astro-minimal.json

feat(opensource): Add astro-minimal.json

---

awesome/digital-nomads/data/malaga.json

feat(digital-nomads): add a new coworking space in Málaga

---

awesome/communities/data/open-source-saturday.json

feat(communities): added Open Source Saturday

---

analytics/partnership.json
awesome/communities/data/tomorrow-devs.json

feat(communities): Add TomorrowDevs

---

awesome/opensource/data/wise-print.json

feat(opensource): added wise-print

---

awesome/communities/data/morrolinux.json

feat(communities): added Morrolinux

---

awesome/communities/data/nix-milano.json

feat(communities): Add nix-milano

---

awesome/communities/data/eventi-tech.json

feat(communities): Add eventi-tech

---

awesome/opensource/projectsveltos.json

feat(opensource): added Projectsveltos

---

awesome/communities/data/italia-js

feat(communities): added ItaliaJS

---

awesome/opensource/data/c14.json

feat(opensource): added c14
